name: metagenomics-env
channels:
  - bioconda
  - conda-forge
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - binutils_impl_linux-64=2.33.1
  - binutils_linux-64=2.33.1
  - bioconductor-decontam=1.10.0
  - bwidget=1.9.11
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.10.14
  - cairo=1.16.0
  - certifi=2020.11.8
  - curl=7.71.1
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=7.3.0
  - gfortran_linux-64=7.3.0
  - glib=2.66.3
  - gmp=6.2.1
  - graphite2=1.3.14
  - gsl=2.6
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - harfbuzz=2.7.2
  - icu=67.1
  - jpeg=9d
  - krb5=1.17.1
  - ld_impl_linux-64=2.33.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.71.1
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.66.3
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libnghttp2=1.41.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - make=4.2.1
  - ncurses=6.2
  - openssl=1.1.1h
  - pandoc=2.11
  - pango=1.42.4
  - pcre=8.44
  - pcre2=10.35
  - pip=20.3
  - pixman=0.40.0
  - python=3.9.0
  - r-ape=5.4_1
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.2.0
  - r-base=4.0.2
  - r-base64enc=0.1_3
  - r-biocmanager=1.30.10
  - r-blob=1.2.1
  - r-bold=1.1.0
  - r-brew=1.0_6
  - r-brio=1.1.0
  - r-broom=0.7.2
  - r-callr=3.5.1
  - r-cellranger=1.1.0
  - r-cli=2.2.0
  - r-clipr=0.7.1
  - r-codetools=0.2_18
  - r-colorspace=2.0_0
  - r-commonmark=1.7
  - r-conditionz=0.1.0
  - r-covr=3.5.1
  - r-cpp11=0.2.4
  - r-crayon=1.3.4
  - r-crosstalk=1.1.0.1
  - r-crul=1.0.0
  - r-curl=4.3
  - r-data.table=1.13.2
  - r-dbi=1.1.0
  - r-dbplyr=2.0.0
  - r-desc=1.2.0
  - r-devtools=2.3.2
  - r-diffobj=0.3.2
  - r-digest=0.6.27
  - r-dplyr=1.0.2
  - r-dt=0.16
  - r-ellipsis=0.3.1
  - r-evaluate=0.14
  - r-fansi=0.4.1
  - r-farver=2.0.3
  - r-fastmatch=1.1_0
  - r-forcats=0.5.0
  - r-foreach=1.5.1
  - r-fs=1.5.0
  - r-generics=0.1.0
  - r-ggplot2=3.3.2
  - r-gh=1.2.0
  - r-git2r=0.27.1
  - r-gitcreds=0.1.0
  - r-glue=1.4.2
  - r-gtable=0.3.0
  - r-haven=2.3.1
  - r-highr=0.8
  - r-hms=0.5.3
  - r-htmltools=0.5.0
  - r-htmlwidgets=1.5.2
  - r-httpcode=0.3.0
  - r-httr=1.4.2
  - r-igraph=1.2.6
  - r-ini=0.3.1
  - r-isoband=0.2.3
  - r-iterators=1.0.13
  - r-jsonlite=1.7.1
  - r-knitr=1.30
  - r-labeling=0.4.2
  - r-later=1.1.0.1
  - r-lattice=0.20_41
  - r-lazyeval=0.2.2
  - r-lifecycle=0.2.0
  - r-lubridate=1.7.9.2
  - r-magrittr=2.0.1
  - r-markdown=1.1
  - r-mass=7.3_53
  - r-matrix=1.2_18
  - r-memoise=1.1.0
  - r-mgcv=1.8_33
  - r-mime=0.9
  - r-modelr=0.1.8
  - r-munsell=0.5.0
  - r-natserv=1.0.0
  - r-nlme=3.1_150
  - r-openssl=1.4.3
  - r-phangorn=2.5.5
  - r-pillar=1.4.7
  - r-pkgbuild=1.1.0
  - r-pkgconfig=2.0.3
  - r-pkgload=1.1.0
  - r-plyr=1.8.6
  - r-praise=1.0.0
  - r-prettyunits=1.1.1
  - r-processx=3.4.5
  - r-progress=1.2.2
  - r-promises=1.1.1
  - r-ps=1.4.0
  - r-purrr=0.3.4
  - r-quadprog=1.5_8
  - r-r6=2.5.0
  - r-rappdirs=0.3.1
  - r-rcmdcheck=1.3.3
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.5
  - r-readr=1.4.0
  - r-readxl=1.3.1
  - r-rematch=1.0.1
  - r-rematch2=2.1.2
  - r-remotes=2.2.0
  - r-rentrez=1.2.3
  - r-reprex=0.3.0
  - r-reshape=0.8.8
  - r-reshape2=1.4.4
  - r-reticulate=1.18
  - r-rex=1.2.0
  - r-ritis=0.9.0
  - r-rlang=0.4.9
  - r-rmarkdown=2.5
  - r-rncl=0.8.4
  - r-rotl=3.0.11
  - r-roxygen2=7.1.1
  - r-rprojroot=2.0.2
  - r-rredlist=0.7.0
  - r-rstudioapi=0.13
  - r-rversions=2.0.2
  - r-rvest=0.3.6
  - r-scales=1.1.1
  - r-selectr=0.4_2
  - r-sessioninfo=1.1.1
  - r-solrium=1.1.4
  - r-stringi=1.5.3
  - r-stringr=1.4.0
  - r-sys=3.4
  - r-taxize=0.9.99
  - r-testthat=3.0.0
  - r-tibble=3.0.4
  - r-tidyr=1.1.2
  - r-tidyselect=1.1.0
  - r-tidyverse=1.3.0
  - r-tinytex=0.27
  - r-triebeard=0.3.0
  - r-urltools=1.7.3
  - r-usethis=1.6.3
  - r-utf8=1.1.4
  - r-uuid=0.1_4
  - r-vctrs=0.3.5
  - r-viridislite=0.3.0
  - r-waldo=0.2.3
  - r-whisker=0.4
  - r-wikidatar=1.4.0
  - r-wikipedir=1.5.0
  - r-wikitaxa=0.4.0
  - r-withr=2.3.0
  - r-worrms=0.4.2
  - r-xfun=0.19
  - r-xml=3.99_0.3
  - r-xml2=1.3.2
  - r-xopen=1.0.0
  - r-yaml=2.2.1
  - r-zeallot=0.1.0
  - r-zoo=1.8_8
  - readline=8.0
  - sed=4.8
  - setuptools=50.3.2
  - sqlite=3.33.0
  - tk=8.6.10
  - tktable=2.10
  - tzdata=2020d
  - wheel=0.36.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
